[phases.install]
cmds = ["npm install", "npm --prefix server install", "npm --prefix client install"]

[phases.build]
cmds = ["npm --prefix client run build"]

[start]
cmd = "node server/src/server.js"
